title: Denny Zhang
description: AI research engineer contributing to AI safety.
url: "https://neveratdennys.github.io"
markdown: kramdown
show_downloads: false
permalink: /writing/:title/
exclude:
  - README.md
  - vendor
  - .bundle
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
